package com.cubeos.meshsat.hub.relay

/**
 * A throwaway test PKI shaped like the Hub's bridge CA (MESHSAT-1157):
 * an EC P-256 CA, a bridge certificate `kit-a` with DNS SAN `kit-a` and
 * serverAuth+clientAuth (what IssueBridgeCert emits since 2026-09-15), and a
 * phone certificate `phone-1` with clientAuth only. Keys are SEC1
 * ("EC PRIVATE KEY"), as the Hub issues them; a PKCS#8 copy of the phone key
 * exercises the other branch of the parser.
 *
 * Generated once with openssl for these tests. It signs nothing real and is
 * trusted by nothing outside this test suite.
 */
object RelayTestPki {
    const val CA_CERT = """-----BEGIN CERTIFICATE-----
MIIBxTCCAWugAwIBAgIUIiPtSHJjj31aF8X+flyHTSTlj6YwCgYIKoZIzj0EAwIw
ODEVMBMGA1UECgwMTWVzaFNhdCBUZXN0MR8wHQYDVQQDDBZNZXNoU2F0IFRlc3Qg
QnJpZGdlIENBMB4XDTI2MDkxNTIwMDQyMloXDTM2MDkxMjIwMDQyMlowODEVMBMG
A1UECgwMTWVzaFNhdCBUZXN0MR8wHQYDVQQDDBZNZXNoU2F0IFRlc3QgQnJpZGdl
IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4UwYZIwm/gzaMfVCLMgF+Wjs
tA+kQgRRCwIxCnvb/d5L9ctUQJ6VanFPIgAlFuvPwtaRUI9CnKD2b8x4iysCAqNT
MFEwHQYDVR0OBBYEFNvX4XNLd2qlDFcvNDgGBwMMgQu5MB8GA1UdIwQYMBaAFNvX
4XNLd2qlDFcvNDgGBwMMgQu5MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwID
SAAwRQIgdUDPGhmyQCcmY3J4j4HEt8JlgbiDg75ivq2/OOk1/98CIQDhVS+rOLXH
p78KiSiypcDEP9jOnhdiXZ/o8CQVDMh/FQ==
-----END CERTIFICATE-----
"""

    /** Bridge `kit-a`: DNS SAN kit-a, EKU serverAuth + clientAuth. */
    const val KIT_A_CERT = """-----BEGIN CERTIFICATE-----
MIIB4jCCAYigAwIBAgIUKvtcGB4oiHPxyafXP7IlwZ5UDfowCgYIKoZIzj0EAwIw
ODEVMBMGA1UECgwMTWVzaFNhdCBUZXN0MR8wHQYDVQQDDBZNZXNoU2F0IFRlc3Qg
QnJpZGdlIENBMB4XDTI2MDkxNTIwMDQyMloXDTM2MDkxMjIwMDQyMlowJzEVMBMG
A1UECgwMTWVzaFNhdCBUZXN0MQ4wDAYDVQQDDAVraXQtYTBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABGVsuReQTJ5jObM4wnqJ4zx9UyGYEFSfIeDa616jf8eF6Fal
4FfmleXAsyt3ApvJ+KmbIU1D5V0soCaDjqC+BHWjgYAwfjAQBgNVHREECTAHggVr
aXQtYTAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwCwYDVR0PBAQDAgeA
MB0GA1UdDgQWBBRBj+De40Dpel4fjI6YbpCghTw47TAfBgNVHSMEGDAWgBTb1+Fz
S3dqpQxXLzQ4BgcDDIELuTAKBggqhkjOPQQDAgNIADBFAiA7AvTvhwkz5wAEl0FL
1oTvPPpU1yZteGehtX9p/GwZ3gIhALbqjPs+6BO/sgIydKrK8++RL6Z+HmZCEXOo
9s21/xiY
-----END CERTIFICATE-----
"""

    const val KIT_A_KEY = """-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIIHKFM22YUlxrKCdDKOUCi2MynQevnFOSALJzJNdr7HWoAoGCCqGSM49
AwEHoUQDQgAEZWy5F5BMnmM5szjCeonjPH1TIZgQVJ8h4NrrXqN/x4XoVqXgV+aV
5cCzK3cCm8n4qZshTUPlXSygJoOOoL4EdQ==
-----END EC PRIVATE KEY-----
"""

    /** Phone `phone-1`: no SAN, EKU clientAuth only. */
    const val PHONE_1_CERT = """-----BEGIN CERTIFICATE-----
MIIByDCCAW2gAwIBAgIUKvtcGB4oiHPxyafXP7IlwZ5UDfswCgYIKoZIzj0EAwIw
ODEVMBMGA1UECgwMTWVzaFNhdCBUZXN0MR8wHQYDVQQDDBZNZXNoU2F0IFRlc3Qg
QnJpZGdlIENBMB4XDTI2MDkxNTIwMDQyMloXDTM2MDkxMjIwMDQyMlowKTEVMBMG
A1UECgwMTWVzaFNhdCBUZXN0MRAwDgYDVQQDDAdwaG9uZS0xMFkwEwYHKoZIzj0C
AQYIKoZIzj0DAQcDQgAEizFDMpl/B9QEZjNM/3TkYR0dYl3BY3u+HDRgvstpD1bv
Iv7BSHicWR9H2tP1oEq75jbhfsN0Ak+BwFy4s30dS6NkMGIwEwYDVR0lBAwwCgYI
KwYBBQUHAwIwCwYDVR0PBAQDAgeAMB0GA1UdDgQWBBSiak755fBXH1ZpH/j+oG83
yifp3jAfBgNVHSMEGDAWgBTb1+FzS3dqpQxXLzQ4BgcDDIELuTAKBggqhkjOPQQD
AgNJADBGAiEA9sFXcqA7bbFjohq+tyGWZOrKRaR1P0gSVHn0Oj+iDD0CIQDxSc0H
s8fjGKW67UKDgNOcK+X9poit9tHA5vh3wOlZjw==
-----END CERTIFICATE-----
"""

    const val PHONE_1_KEY = """-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIDE+T2ZMY97Nr1MRQLLD5wRH6muVEUSwn0dbx3QnRT63oAoGCCqGSM49
AwEHoUQDQgAEizFDMpl/B9QEZjNM/3TkYR0dYl3BY3u+HDRgvstpD1bvIv7BSHic
WR9H2tP1oEq75jbhfsN0Ak+BwFy4s30dSw==
-----END EC PRIVATE KEY-----
"""

    /** The same phone key as PKCS#8. */
    const val PHONE_1_KEY_PKCS8 = """-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgMT5PZkxj3s2vUxFA
ssPnBEfqa5URRLCfR1vHdCdFPrehRANCAASLMUMymX8H1ARmM0z/dORhHR1iXcFj
e74cNGC+y2kPVu8i/sFIeJxZH0fa0/WgSrvmNuF+w3QCT4HAXLizfR1L
-----END PRIVATE KEY-----
"""
}
