package net.meshsat.android.crypto

import android.content.Context
import net.meshsat.android.data.AppDatabase
import net.meshsat.android.data.BridgeTrustDao
import net.meshsat.android.data.BridgeTrustEntity
import net.meshsat.android.data.ConversationKey
import net.meshsat.android.data.ConversationKeyDao
import net.meshsat.android.data.ProviderCredential
import net.meshsat.android.data.ProviderCredentialDao
import net.meshsat.android.routing.rawToEd25519Public
import java.security.Signature

/**
 * Imports key bundles from `meshsat://key/` URLs generated by the MeshSat bridge.
 *
 * Two bundle formats are supported:
 *
 * **v1 (legacy, 86-byte header)** — no embedded signing pubkey, signature cannot be
 * verified locally. Imported as [TrustStatus.UNVERIFIED_V1] — the user sees a warning
 * but the keys still land in the conversation key store for backward compatibility
 * with older bridges.
 * ```
 * Version(1)=0x01 | BridgeHash(16) | Timestamp(4) | EntryCount(1) | Signature(64)
 * Per entry:     ChannelType(1) | AddrLen(1) | Address(N) | AESKey(32)
 * ```
 *
 * **v2 (new, 118-byte header)** — embeds the Ed25519 signing pubkey inside the signed
 * payload. TOFU-pinned: first import from a given `bridgeHash` stores the pubkey in
 * the `bridge_trust` table; subsequent imports verify the signature against the
 * stored pubkey and reject mismatches.
 * ```
 * Version(1)=0x02 | BridgeHash(16) | Timestamp(4) | EntryCount(1) | SigningPubkey(32) | Signature(64)
 * Per entry:     ChannelType(1) | AddrLen(1) | Address(N) | AESKey(32)
 * ```
 *
 * The signature covers all bytes EXCEPT the 64 signature bytes themselves (including
 * `SigningPubkey` in v2, so the pubkey cannot be swapped without invalidating the
 * signature).
 *
 * MESHSAT-495.
 */
object KeyBundleImporter {

    private const val URL_PREFIX = "meshsat://key/"
    private const val V1 = 0x01.toByte()
    private const val V2 = 0x02.toByte()

    // Shared header prefix layout
    private const val VERSION_OFF = 0
    private const val BRIDGE_HASH_OFF = 1
    private const val BRIDGE_HASH_LEN = 16
    private const val TIMESTAMP_OFF = 17
    private const val TIMESTAMP_LEN = 4
    private const val ENTRY_COUNT_OFF = 21

    // v1: signature immediately after entry count
    private const val V1_SIGNATURE_OFF = 22
    private const val V1_HEADER_SIZE = 86 // 22 + 64

    // v2: signing pubkey, then signature
    private const val V2_PUBKEY_OFF = 22
    private const val V2_PUBKEY_LEN = 32
    private const val V2_SIGNATURE_OFF = 54
    private const val V2_HEADER_SIZE = 118 // 54 + 64

    private const val SIGNATURE_SIZE = 64
    private const val AES_KEY_SIZE = 32

    private val CHANNEL_TYPES = mapOf(
        0x00.toByte() to "sms",
        0x01.toByte() to "mesh",
        0x02.toByte() to "iridium",
        0x04.toByte() to "zigbee",
        0x05.toByte() to "mqtt",
        0x06.toByte() to "webhook",
    )

    /** Trust status for a successful import. */
    enum class TrustStatus {
        /** First import from this bridge hash — signature verified, pubkey pinned. */
        NEW_TRUSTED,

        /** Second or later import from this bridge hash — signature matches pinned pubkey. */
        EXISTING_TRUSTED,

        /**
         * v1 (legacy) bundle — no embedded pubkey, signature cannot be verified locally.
         * Keys are imported for backward compatibility but the user sees a warning.
         */
        UNVERIFIED_V1,
    }

    /** Result of an import attempt. UI handles each variant distinctly. */
    sealed class ImportResult {
        /** Bundle was valid; keys were imported. */
        data class Success(
            val count: Int,
            val status: TrustStatus,
            val bridgeHashHex: String,
        ) : ImportResult()

        /**
         * v2 bundle presented a DIFFERENT Ed25519 pubkey than the one previously pinned
         * for this `bridgeHash`. Could be intentional key rotation or impersonation.
         * No keys imported — UI should prompt user to accept (re-pin) or reject.
         */
        data class KeyMismatch(
            val bridgeHashHex: String,
            val storedPubkey: ByteArray,
            val presentedPubkey: ByteArray,
            val firstSeen: Long,
        ) : ImportResult() {
            override fun equals(other: Any?): Boolean {
                if (this === other) return true
                if (javaClass != other?.javaClass) return false
                other as KeyMismatch
                return bridgeHashHex == other.bridgeHashHex &&
                    storedPubkey.contentEquals(other.storedPubkey) &&
                    presentedPubkey.contentEquals(other.presentedPubkey) &&
                    firstSeen == other.firstSeen
            }

            override fun hashCode(): Int {
                var h = bridgeHashHex.hashCode()
                h = 31 * h + storedPubkey.contentHashCode()
                h = 31 * h + presentedPubkey.contentHashCode()
                h = 31 * h + firstSeen.hashCode()
                return h
            }
        }

        /** v2 signature failed Ed25519 verification. Forged or tampered bundle. */
        data class InvalidSignature(val reason: String) : ImportResult()

        /** Bundle was malformed — wrong prefix, truncated, unsupported version, etc. */
        data class Malformed(val reason: String) : ImportResult()
    }

    /**
     * Import keys from a `meshsat://key/` URL with TOFU verification.
     *
     * For v2 bundles: verifies signature, pins pubkey on first use, rejects mismatches.
     * For v1 bundles: imports without verification (backward compat), status = UNVERIFIED_V1.
     *
     * Call [importFromURLForceRepin] to intentionally overwrite a pinned pubkey
     * (e.g., after legitimate bridge key rotation).
     */
    suspend fun importFromURL(url: String, context: Context): ImportResult {
        val db = AppDatabase.getInstance(context)
        return importFromURL(
            url = url,
            trustDao = db.bridgeTrustDao(),
            convKeyDao = db.conversationKeyDao(),
            credDao = db.providerCredentialDao(),
            forceRepin = false,
        )
    }

    /**
     * Import with forced re-pin — overwrites any existing trust record for this
     * bridge hash. Use only after the user has explicitly confirmed intentional
     * key rotation in response to a [ImportResult.KeyMismatch] warning.
     */
    suspend fun importFromURLForceRepin(url: String, context: Context): ImportResult {
        val db = AppDatabase.getInstance(context)
        return importFromURL(
            url = url,
            trustDao = db.bridgeTrustDao(),
            convKeyDao = db.conversationKeyDao(),
            credDao = db.providerCredentialDao(),
            forceRepin = true,
        )
    }

    /**
     * Pure, Android-Context-free import entry point for testing and DI.
     * Takes DAO interfaces directly so unit tests can supply fakes.
     */
    internal suspend fun importFromURL(
        url: String,
        trustDao: BridgeTrustDao,
        convKeyDao: ConversationKeyDao,
        credDao: ProviderCredentialDao,
        forceRepin: Boolean = false,
        now: Long = System.currentTimeMillis(),
    ): ImportResult {
        if (!url.startsWith(URL_PREFIX)) {
            return ImportResult.Malformed("Not a meshsat key URL")
        }

        val encoded = url.substring(URL_PREFIX.length)
        val data = try {
            // java.util.Base64 (API 26+) is used instead of android.util.Base64
            // so this class is testable on the JVM without Robolectric.
            // URL decoder accepts both padded and unpadded input.
            java.util.Base64.getUrlDecoder().decode(encoded)
        } catch (e: IllegalArgumentException) {
            return ImportResult.Malformed("Base64 decode failed: ${e.message}")
        }

        if (data.size < V1_HEADER_SIZE) {
            return ImportResult.Malformed("Bundle too short: ${data.size} bytes")
        }

        return when (data[VERSION_OFF]) {
            V1 -> importV1(data, convKeyDao, credDao)
            V2 -> importV2(data, trustDao, convKeyDao, credDao, forceRepin, now)
            else -> ImportResult.Malformed("Unsupported bundle version: 0x${"%02x".format(data[0])}")
        }
    }

    private suspend fun importV1(
        data: ByteArray,
        convKeyDao: ConversationKeyDao,
        credDao: ProviderCredentialDao,
    ): ImportResult {
        val bridgeHash = data.sliceArray(BRIDGE_HASH_OFF until BRIDGE_HASH_OFF + BRIDGE_HASH_LEN)
        val entryCount = data[ENTRY_COUNT_OFF].toInt() and 0xFF
        val bridgeHashHex = bridgeHash.toHexLocal()

        val imported = try {
            writeEntriesToDb(
                data = data,
                entriesStartOffset = V1_HEADER_SIZE,
                entryCount = entryCount,
                bridgeHashHex = bridgeHashHex,
                convKeyDao = convKeyDao,
                credDao = credDao,
            )
        } catch (e: Exception) {
            return ImportResult.Malformed("Entry parse failed: ${e.message}")
        }

        // v1: no embedded pubkey, cannot verify, do not create trust record.
        // Keys are imported but UI should flag as UNVERIFIED.
        return ImportResult.Success(imported, TrustStatus.UNVERIFIED_V1, bridgeHashHex)
    }

    private suspend fun importV2(
        data: ByteArray,
        trustDao: BridgeTrustDao,
        convKeyDao: ConversationKeyDao,
        credDao: ProviderCredentialDao,
        forceRepin: Boolean,
        now: Long,
    ): ImportResult {
        if (data.size < V2_HEADER_SIZE) {
            return ImportResult.Malformed("v2 bundle too short: ${data.size} bytes (need $V2_HEADER_SIZE)")
        }

        val bridgeHash = data.sliceArray(BRIDGE_HASH_OFF until BRIDGE_HASH_OFF + BRIDGE_HASH_LEN)
        val bridgeHashHex = bridgeHash.toHexLocal()
        val entryCount = data[ENTRY_COUNT_OFF].toInt() and 0xFF
        val presentedPubkey = data.sliceArray(V2_PUBKEY_OFF until V2_PUBKEY_OFF + V2_PUBKEY_LEN)
        val signature = data.sliceArray(V2_SIGNATURE_OFF until V2_SIGNATURE_OFF + SIGNATURE_SIZE)

        // Reconstruct the signed bytes: everything before the signature + everything after.
        val signedContent = ByteArray(data.size - SIGNATURE_SIZE)
        System.arraycopy(data, 0, signedContent, 0, V2_SIGNATURE_OFF)
        val tailStart = V2_SIGNATURE_OFF + SIGNATURE_SIZE
        val tailLen = data.size - tailStart
        if (tailLen > 0) {
            System.arraycopy(data, tailStart, signedContent, V2_SIGNATURE_OFF, tailLen)
        }

        // Verify the signature using the presented pubkey (before any trust check).
        // An attacker could swap both the pubkey and resign — TOFU catches that later,
        // but malformed / tampered bundles are caught here.
        val sigValid = try {
            val pubKey = rawToEd25519Public(presentedPubkey)
            val sig = Signature.getInstance("Ed25519", "BC")
            sig.initVerify(pubKey)
            sig.update(signedContent)
            sig.verify(signature)
        } catch (e: Exception) {
            return ImportResult.InvalidSignature("Signature verification error: ${e.message}")
        }

        if (!sigValid) {
            return ImportResult.InvalidSignature("Ed25519 signature does not match bundle contents")
        }

        // Signature is valid for the presented pubkey. Now apply TOFU.
        val existing = trustDao.get(bridgeHashHex)

        val status: TrustStatus = when {
            existing == null -> {
                // First time seeing this bridge — pin the pubkey.
                trustDao.upsert(
                    BridgeTrustEntity(
                        bridgeHash = bridgeHashHex,
                        pubkey = presentedPubkey,
                        firstSeen = now,
                        lastSeen = now,
                        label = "Bridge ${bridgeHashHex.take(8)}",
                        importCount = 1,
                    ),
                )
                TrustStatus.NEW_TRUSTED
            }

            existing.pubkey.contentEquals(presentedPubkey) -> {
                // Returning bridge with matching pubkey — update last-seen.
                trustDao.upsert(
                    existing.copy(
                        lastSeen = now,
                        importCount = existing.importCount + 1,
                    ),
                )
                TrustStatus.EXISTING_TRUSTED
            }

            forceRepin -> {
                // User explicitly confirmed key rotation — overwrite the pinned key.
                trustDao.upsert(
                    existing.copy(
                        pubkey = presentedPubkey,
                        lastSeen = now,
                        importCount = existing.importCount + 1,
                    ),
                )
                TrustStatus.NEW_TRUSTED
            }

            else -> {
                // Pubkey changed without force — possible impersonation. Reject.
                return ImportResult.KeyMismatch(
                    bridgeHashHex = bridgeHashHex,
                    storedPubkey = existing.pubkey,
                    presentedPubkey = presentedPubkey,
                    firstSeen = existing.firstSeen,
                )
            }
        }

        val imported = try {
            writeEntriesToDb(
                data = data,
                entriesStartOffset = V2_HEADER_SIZE,
                entryCount = entryCount,
                bridgeHashHex = bridgeHashHex,
                convKeyDao = convKeyDao,
                credDao = credDao,
            )
        } catch (e: Exception) {
            return ImportResult.Malformed("Entry parse failed: ${e.message}")
        }

        return ImportResult.Success(imported, status, bridgeHashHex)
    }

    /**
     * Parse entries starting at [entriesStartOffset] and upsert them as both
     * `ConversationKey` and `ProviderCredential` rows. Returns the number of
     * entries imported.
     */
    private suspend fun writeEntriesToDb(
        data: ByteArray,
        entriesStartOffset: Int,
        entryCount: Int,
        bridgeHashHex: String,
        convKeyDao: ConversationKeyDao,
        credDao: ProviderCredentialDao,
    ): Int {
        var offset = entriesStartOffset
        var imported = 0

        for (i in 0 until entryCount) {
            require(offset + 2 <= data.size) { "Truncated entry $i" }
            val channelType = data[offset]
            val addrLen = data[offset + 1].toInt() and 0xFF
            offset += 2

            require(offset + addrLen + AES_KEY_SIZE <= data.size) { "Truncated entry $i data" }
            val address = String(data, offset, addrLen, Charsets.UTF_8)
            offset += addrLen

            val aesKey = data.sliceArray(offset until offset + AES_KEY_SIZE)
            offset += AES_KEY_SIZE

            val hexKey = aesKey.joinToString("") { "%02x".format(it) }
            val channelName = CHANNEL_TYPES[channelType] ?: "unknown"

            convKeyDao.upsert(
                ConversationKey(
                    sender = address,
                    hexKey = hexKey,
                    label = "Bridge $channelName (${bridgeHashHex.take(8)})",
                ),
            )

            credDao.upsert(
                ProviderCredential(
                    id = "${bridgeHashHex.take(8)}_${channelName}_${address.hashCode().toString(16)}",
                    provider = channelName,
                    name = "Key for $address (bridge ${bridgeHashHex.take(8)})",
                    credType = "aes_key",
                    encryptedData = aesKey,
                    source = "qr",
                    version = 1,
                ),
            )

            imported++
        }

        return imported
    }

    private fun ByteArray.toHexLocal(): String =
        joinToString("") { "%02x".format(it) }
}
